apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: banco-repli
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: db
        ports:
        - containerPort: 5432